### ISSUE TITLE
languages.getLanguageInfo().direction always returns ltr

### ISSUE THREAD

**Issue by angleman** [joker-x/languages.js#1]
Thanks for making this language util available!

I ran into the following challenge:

```
languages = require('languages');
info = languages.getLanguageInfo('ar');
console.log(info.direction); // returns 'ltr'. 'rtl' was expected
```

consider replacing line 30 in languages.js:

```
"rtl": ["ar","dv","fa","ha","he","ks","ku","ps","ur","yi"]
```

with

```
"rtl": {ar:1,dv:1,fa:1,ha:1,he:1,ks:1,ku:1,ps:1,ur:1,yi:1}
```

and replacing lines 222-224 in languages.js

```
  var result = "ltr";
  if (langs.rtl.indexOf(langcode) != -1) result = "rtl";
  return result;
```

with

```
  return (langs.rtl[langcode]) ? 'rtl' : 'ltr';
```

This should be faster, reduce code foot print and correct the bug :-)

**Comment by joker-x** [comment]
I cannot reproduce the bug. Your code return me 'rtl' in the browser and in node v0.8.4...

At any rate, your change is an improvement and i will merge it. 

Thanks!
